os: Visual Studio 2015 RC

environment:
  NuGetApiKey:
    secure: HFUEQanhaxHV/sRQYznQqg7LToxSGeIoSvrmyY29PJ1eDbXxUuYrEQ6MPAsZIQFT

configuration: Release


build_script:
  - ps: .\appveyor.ps1

artifacts:
  - path: 'vs\AlfredTrx\AlfredTrx\bin\Release\*'