os: Visual Studio 2015 RC

environment:
  NuGetApiKey:
    secure: HFUEQanhaxHV/sRQYznQqg7LToxSGeIoSvrmyY29PJ1eDbXxUuYrEQ6MPAsZIQFT

configuration: Release

before_build:
- nuget restore src\Geoffrey.sln

build_script:
  - ps: .\appveyor.ps1

artifacts:
  - path: 'src\GeoffreyTrx\bin\Release\*'