os: Visual Studio 2015

environment:
  NuGetApiKey:
    secure: HFUEQanhaxHV/sRQYznQqg7LToxSGeIoSvrmyY29PJ1eDbXxUuYrEQ6MPAsZIQFT

configuration: Release

before_build:
- nuget restore projects\Geoffrey.sln

build_script:
  - ps: .\appveyor.ps1

artifacts:
  - path: 'OutputRoot\_nuget-pkg\*.nupkg'
  - path: 'OutputRoot\GeoffreyTrx.vsix'
  - path: 'OutputRoot\geoffrey.nuspec'
  - path: 'OutputRoot\geoffrey.psm1'